/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simulador.gui;

import javax.swing.JOptionPane;
import simulador.estructuras.MiCola;
import simulador.gui.MiArbolModelo;
import simulador.modelo.Archivo;
import simulador.modelo.Bloque;
import simulador.modelo.Directoria; // ¡Ahora sí la encontrará!
import simulador.modelo.DiscoSD;
import simulador.modelo.NodoSistema;
import simulador.modelo.Proceso;

/**
 *
 * @author estab
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Directoria raiz;
    private DiscoSD miDisco;
    private MiArbolModelo modeloArbol;
    private javax.swing.JLabel[] etiquetasBloques;
    private int posicionCabezal = 0; 
    private boolean direccionSubida = true;
    private MiCola<Proceso> colaDeProcesos;
    public VentanaPrincipal() {
        initComponents();
        this.miDisco = new DiscoSD(100);
        
this.colaDeProcesos = new MiCola<>();
this.raiz = new Directoria("C:");

// 3. (Opcional) Agrega datos de prueba para ver si funciona
Directoria dirUsuario = new Directoria("Usuarios");
this.raiz.agregarHijo(dirUsuario);
this.raiz.agregarHijo(new Archivo("boot.txt", 1));
dirUsuario.agregarHijo(new Archivo("documento.pdf", 5));

// 4. Crea el "Traductor" (TreeModel) pasándole tu raíz
this.modeloArbol = new MiArbolModelo(this.raiz);


jTree1.setModel(this.modeloArbol);
actualizarTablaFAT();
this.etiquetasBloques = new javax.swing.JLabel[miDisco.getNumBloques()];


for (int i = 0; i < miDisco.getNumBloques(); i++) {
    javax.swing.JLabel etiquetaCuadro = new javax.swing.JLabel();

    etiquetaCuadro.setOpaque(true); 
    etiquetaCuadro.setBackground(java.awt.Color.GREEN); 
    etiquetaCuadro.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK)); 
    this.etiquetasBloques[i] = etiquetaCuadro; 
    this.jPanel3.add(etiquetaCuadro);  
    
}
actualizarVisualizadorGrafico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cboxPolitica = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cboxModo = new javax.swing.JComboBox<>();
        btnRenombrar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Propietario", "Siguiente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Tabla de Asignacion", jPanel4);

        jPanel3.setLayout(new java.awt.GridLayout(10, 10));
        jTabbedPane2.addTab("Visualizador de Disco", jPanel3);

        jButton4.setText("Crear Proceso");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Ejecutar Ciclo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        cboxPolitica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "SSTF", "SCAN", "C-SCAN" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxPolitica, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxPolitica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );

        jTabbedPane2.addTab("Gestor de Procesos", jPanel2);

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton3)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jButton1.setText("Crear Directorio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear Archivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cboxModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        cboxModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxModoActionPerformed(evt);
            }
        });

        btnRenombrar.setText("Renombrar");
        btnRenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenombrarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxModo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRenombrar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(btnRenombrar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCargar))))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String modo = cboxModo.getSelectedItem().toString();
    if (modo.equals("Usuario")) {
        JOptionPane.showMessageDialog(this, "Error: Permisos insuficientes. Solo el Administrador puede crear directorios.", "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
        return; // Detiene la ejecución aquí
    }
// 1. Obtener el nodo que está seleccionado en el árbol
// getLastSelectedPathComponent() nos da el objeto (Archivo o Directorio) seleccionado
Object nodoSeleccionado = jTree1.getLastSelectedPathComponent();

// 2. Verificar que haya algo seleccionado Y que sea un Directorio
// (No podemos crear un directorio dentro de un archivo)
if (nodoSeleccionado != null && nodoSeleccionado instanceof Directoria) {

    // 3. Si es un Directorio, lo "casteamos" para poder usarlo
    Directoria directorioPadre = (Directoria) nodoSeleccionado;

    // 4. Pedir el nombre del nuevo directorio al usuario
    String nombreNuevo = JOptionPane.showInputDialog(this, 
                                                   "Escribe el nombre del nuevo directorio:", 
                                                   "Crear Directorio", 
                                                   JOptionPane.PLAIN_MESSAGE);

    // 5. Verificar que el usuario no haya cancelado o escrito un nombre vacío
    if (nombreNuevo != null && !nombreNuevo.trim().isEmpty()) {

        // 6. Crear el nuevo Directorio (en nuestra lógica/modelo)
        Directoria nuevoDir = new Directoria(nombreNuevo.trim());

        // 7. Añadirlo al padre (en nuestra lógica/modelo)
        directorioPadre.agregarHijo(nuevoDir);

        // 8. ¡EL PASO MÁGICO! Actualizar la Vista (el JTree)
        // updateUI() le dice al JTree que vuelva a leer todo el modelo y se redibuje
        jTree1.updateUI();

    }
} else {
    // Si no seleccionó nada, o si seleccionó un archivo
    JOptionPane.showMessageDialog(this, 
                                "Por favor, selecciona un directorio en el árbol primero.", 
                                "Error", 
                                JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// --- CANDADO DE SEGURIDAD ---
    if (cboxModo.getSelectedItem().toString().equals("Usuario")) {
        JOptionPane.showMessageDialog(this, "Error: Los usuarios no pueden crear archivos en el disco.", "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
        return;
    }        
// 1. Obtener el directorio padre seleccionado
Object nodoSeleccionado = jTree1.getLastSelectedPathComponent();
if (nodoSeleccionado == null || !(nodoSeleccionado instanceof Directoria)) {
    JOptionPane.showMessageDialog(this, "Por favor, selecciona un directorio en el árbol primero.", "Error", JOptionPane.ERROR_MESSAGE);
    return; // Detiene la ejecución
}
Directoria directorioPadre = (Directoria) nodoSeleccionado;

// 2. Pedir nombre y TAMAÑO del archivo
String nombreArchivo = JOptionPane.showInputDialog(this, "Nombre del archivo:", "Crear Archivo", JOptionPane.PLAIN_MESSAGE);
if (nombreArchivo == null || nombreArchivo.trim().isEmpty()) {
    return; // Canceló o no escribió nada
}

// 2.b. Pedimos el TAMAÑO (esto es clave)
String tamanoStr = JOptionPane.showInputDialog(this, "Tamaño en bloques:", "Crear Archivo", JOptionPane.PLAIN_MESSAGE);
int tamanoEnBloques;
try {
    tamanoEnBloques = Integer.parseInt(tamanoStr);
    if (tamanoEnBloques <= 0) throw new NumberFormatException();
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Tamaño inválido. Debe ser un número positivo.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// --- INICIO DE LA LÓGICA DE DISCO ---

// 3. Crear el objeto Archivo (en memoria)
Archivo nuevoArchivo = new Archivo(nombreArchivo.trim(), tamanoEnBloques);
int bloquePrevioId = -1;
int bloqueInicialId = -1;

// 4. Asignar bloques en el disco (el "cerebro" del simulador)
for (int i = 0; i < tamanoEnBloques; i++) {
    // 4.1. Buscar un bloque libre en nuestro DiscoSD
    int bloqueLibreId = miDisco.encontrarBloqueLibre();
    
    if (bloqueLibreId == -1) {
        // ¡DISCO LLENO!
        JOptionPane.showMessageDialog(this, "¡Error! Disco lleno. No se pudo crear el archivo.", "Disco Lleno", JOptionPane.ERROR_MESSAGE);
        
        // ¡Importante! Liberamos los bloques que ya habíamos asignado a este archivo
        // para que no queden "basura" en el disco.
        if (bloqueInicialId != -1) {
            miDisco.liberarCadena(bloqueInicialId);
        }
        return; // Detenemos todo
    }
    
    // 4.2. Si encontramos bloque, lo "ocupamos"
    Bloque bloqueActual = miDisco.getBloque(bloqueLibreId);
    
    // El último bloque apunta a -1 (fin de la cadena)
    bloqueActual.asignar(nuevoArchivo.getNombre(), -1); 
    
    // 4.3. Encadenar la lista de bloques
    if (i == 0) {
        // Si es el primer bloque, guardamos su ID en el objeto Archivo
        bloqueInicialId = bloqueLibreId;
        nuevoArchivo.setBloqueInicial(bloqueInicialId);
    } else {
        // Si no es el primero, le decimos al bloque *anterior* que apunte a este nuevo bloque
        Bloque bloquePrevio = miDisco.getBloque(bloquePrevioId);
        bloquePrevio.setSiguienteBloque(bloqueLibreId);
    }
    
    // El bloque actual se convierte en el "previo" para la siguiente vuelta del bucle
    bloquePrevioId = bloqueLibreId;
}

// 5. Si el bucle terminó sin errores, ¡el archivo se creó en el disco!
//    Ahora lo agregamos al árbol (modelo)
directorioPadre.agregarHijo(nuevoArchivo);

// 6. Actualizar la GUI (vista)
jTree1.updateUI();
actualizarTablaFAT();
actualizarVisualizadorGrafico();

// 7. (Avance) En el siguiente paso, aquí llamaremos a las funciones
//    para actualizar la tabla y los cuadritos de colores.
//
// actualizarTablaFAT();
// actualizarVisualizadorGrafico();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if (cboxModo.getSelectedItem().toString().equals("Usuario")) {
        JOptionPane.showMessageDialog(this, "Error: No tienes permiso para eliminar archivos.", "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
        return;
    }      
// 1. Obtener el nodo que está seleccionado en el árbol
Object nodoSeleccionado = jTree1.getLastSelectedPathComponent();

// 2. Verificar que haya algo seleccionado
if (nodoSeleccionado == null) {
    JOptionPane.showMessageDialog(this, "Por favor, selecciona un archivo o directorio para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// 3. No se puede eliminar la raíz "C:"
if (nodoSeleccionado instanceof Directoria && ((Directoria) nodoSeleccionado).getPadre() == null) {
    JOptionPane.showMessageDialog(this, "No se puede eliminar el directorio raíz (C:).", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// 4. Pedir confirmación antes de borrar
int confirmacion = JOptionPane.showConfirmDialog(this, 
                                             "¿Estás seguro de que quieres eliminar '" + nodoSeleccionado + "'?", 
                                             "Confirmar Eliminación", 
                                             JOptionPane.YES_NO_OPTION, 
                                             JOptionPane.WARNING_MESSAGE);

if (confirmacion != JOptionPane.YES_OPTION) {
    return; // Si no confirma, no hacemos nada
}

// 5. Lógica de eliminación
Directoria padre = ((NodoSistema) nodoSeleccionado).getPadre();

// --- CASO A: Es un Archivo ---
if (nodoSeleccionado instanceof Archivo) {
    Archivo archivoAEliminar = (Archivo) nodoSeleccionado;
    
    // 5.1. Liberamos los bloques en el disco
    int bloqueInicial = archivoAEliminar.getBloqueInicial();
    if (bloqueInicial != -1) {
        miDisco.liberarCadena(bloqueInicial);
    }
    
    // 5.2. Lo quitamos del árbol (modelo)
    padre.eliminarHijo(archivoAEliminar);

// --- CASO B: Es un Directorio ---
} else if (nodoSeleccionado instanceof Directoria) {
    Directoria dirAEliminar = (Directoria) nodoSeleccionado;
    
    // 5.3. Verificamos si el directorio está vacío
    if (dirAEliminar.getCantidadHijos() == 0) {
        // Si está vacío, lo quitamos del árbol (modelo)
        padre.eliminarHijo(dirAEliminar);
    } else {
        // Si no está vacío, mostramos un error
        JOptionPane.showMessageDialog(this, "No se puede eliminar un directorio que no está vacío.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// 6. Actualizar la GUI (vista)
jTree1.updateUI();
actualizarTablaFAT();
actualizarVisualizadorGrafico();

// 7. (Avance) Aquí también actualizaremos la tabla y los cuadritos
// actualizarTablaFAT();
// actualizarVisualizadorGrafico();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (this.colaDeProcesos.estaVacia()) {
            jTextArea1.append("--- CPU Ociosa (Cola vacía) ---\n");
            return;
        }
        // 1. USAMOS EL PLANIFICADOR PARA ELEGIR EL PROCESO
        // (Esto reemplaza al simple desencolar)
        Proceso p = seleccionarProcesoSegunPolitica();

        if (p == null) return; // Seguridad

        // 2. Actualizamos la posición del cabezal (Simulación del movimiento)
        int bloqueDestino = p.getArchivoQueUsa().getBloqueInicial();
        this.posicionCabezal = bloqueDestino;

        // 3. Ejecutar ciclo
        p.ejecutarCiclo();

        // Log visual con detalles del disco
        jTextArea1.append("[CPU] Ejecutando: " + p.getNombre()
            + " | Archivo en Bloque: " + bloqueDestino
            + " | Algoritmo: " + cboxPolitica.getSelectedItem() + "\n");

        // 4. Verificar si terminó
        if (p.haTerminado()) {
            jTextArea1.append("   ★ [FIN] " + p.getNombre() + " ha terminado.\n");
        } else {
            // Si no terminó, vuelve a la cola
            this.colaDeProcesos.encolar(p);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nombreProc = JOptionPane.showInputDialog(this, "Nombre del proceso (ej. 'Word'):");
        if (nombreProc == null || nombreProc.trim().isEmpty()) return;

        String nombreArch = JOptionPane.showInputDialog(this, "Nombre del archivo a usar:");
        if (nombreArch == null || nombreArch.trim().isEmpty()) return;

        // 2. Buscar el archivo en el árbol (Usando el método que agregamos en Directoria)
        Archivo archivo = raiz.buscarArchivo(nombreArch.trim());

        if (archivo == null) {
            JOptionPane.showMessageDialog(this, "El archivo no existe. Créalo primero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Crear el proceso (Asumimos 5 ciclos de duración por defecto)
        Proceso p = new Proceso(nombreProc, archivo, 5);

        // 4. Añadirlo a la cola
        this.colaDeProcesos.encolar(p);

        // 5. Mostrar en el log (Asegúrate de que tu TextArea se llame jTextArea1 o cámbialo aquí)
        jTextArea1.append(">> [NUEVO] Proceso " + p.getNombre() + " encolado.\n");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenombrarActionPerformed
    // 1. SEGURIDAD: Verificar modo Administrador
    if (cboxModo.getSelectedItem().toString().equals("Usuario")) {
        JOptionPane.showMessageDialog(this, "Error: Solo el Administrador puede renombrar archivos.", "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Obtener selección
    Object nodoSeleccionado = jTree1.getLastSelectedPathComponent();
    if (nodoSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Selecciona un archivo o directorio primero.");
        return;
    }
    
    // No se puede renombrar el disco C: (Raíz)
    simulador.modelo.NodoSistema nodo = (simulador.modelo.NodoSistema) nodoSeleccionado;
    if (nodo.getPadre() == null) {
        JOptionPane.showMessageDialog(this, "No puedes renombrar la raíz.");
        return;
    }

    // 3. Pedir nuevo nombre
    String nuevoNombre = JOptionPane.showInputDialog(this, "Nuevo nombre para '" + nodo.toString() + "':", nodo.toString());
    
    if (nuevoNombre != null && !nuevoNombre.trim().isEmpty()) {
        // 4. Aplicar cambio
        nodo.setNombre(nuevoNombre.trim());
        
        // 5. Actualizar visuales
        jTree1.updateUI();           // Refresca el árbol
        actualizarTablaFAT();        // Refresca la tabla
    }
    }//GEN-LAST:event_btnRenombrarActionPerformed

    private void cboxModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxModoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
                                         
    // Solo Admin puede guardar
    if (cboxModo.getSelectedItem().toString().equals("Usuario")) {
         JOptionPane.showMessageDialog(this, "Solo Admin puede guardar.");
         return;
    }
    // Llamamos a nuestra clase nueva
    simulador.logica.GestorDatos.guardarSistema(this.raiz, this.miDisco);

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
                                           
    Object[] datos = simulador.logica.GestorDatos.cargarSistema();
    
    if (datos != null) {
        // Recuperamos los objetos
        this.raiz = (simulador.modelo.Directoria) datos[0];
        this.miDisco = (simulador.modelo.DiscoSD) datos[1];
        
        // IMPORTANTÍSIMO: Reconectar el modelo visual
        this.modeloArbol = new simulador.gui.MiArbolModelo(this.raiz);
        jTree1.setModel(this.modeloArbol);
        
        // Actualizar visuales
        jTree1.updateUI();
        actualizarTablaFAT();
        actualizarVisualizadorGrafico();
    }

    }//GEN-LAST:event_btnCargarActionPerformed
/**
 * Método auxiliar que vuelca la cola en una lista para poder buscar.
 */
private simulador.estructuras.MiListaEnlazada<simulador.modelo.Proceso> obtenerProcesosEnEspera() {
    simulador.estructuras.MiListaEnlazada<simulador.modelo.Proceso> listaTemporal = new simulador.estructuras.MiListaEnlazada<>();
    
    // Vaciamos la cola y llenamos la lista temporal
    while (!colaDeProcesos.estaVacia()) {
        listaTemporal.agregar(colaDeProcesos.desencolar());
    }
    return listaTemporal;
}
    private simulador.modelo.Proceso seleccionarProcesoSegunPolitica() {
    // 1. Pasamos todo a una lista para poder buscar
    simulador.estructuras.MiListaEnlazada<simulador.modelo.Proceso> lista = obtenerProcesosEnEspera();
    
    if (lista.getTamano() == 0) return null;

    // Asegúrate de usar el nombre correcto de tu variable (jComboBox1, cboxPolitica, etc.)
    String politica = cboxPolitica.getSelectedItem().toString(); 
    simulador.modelo.Proceso elegido = null;

    // --- ALGORITMO FIFO ---
    if (politica.equals("FIFO")) {
        elegido = lista.get(0);
    } 
    // --- ALGORITMO SSTF ---
    else if (politica.equals("SSTF")) {
        int menorDistancia = Integer.MAX_VALUE;
        for (int i = 0; i < lista.getTamano(); i++) {
            simulador.modelo.Proceso p = lista.get(i);
            int dist = Math.abs(p.getArchivoQueUsa().getBloqueInicial() - this.posicionCabezal);
            if (dist < menorDistancia) {
                menorDistancia = dist;
                elegido = p;
            }
        }
    }
    // --- ALGORITMO SCAN ---
    else if (politica.equals("SCAN")) {
        simulador.estructuras.MiListaEnlazada<simulador.modelo.Proceso> arriba = new simulador.estructuras.MiListaEnlazada<>();
        simulador.estructuras.MiListaEnlazada<simulador.modelo.Proceso> abajo = new simulador.estructuras.MiListaEnlazada<>();

        for (int i = 0; i < lista.getTamano(); i++) {
            simulador.modelo.Proceso p = lista.get(i);
            if (p.getArchivoQueUsa().getBloqueInicial() >= this.posicionCabezal) {
                arriba.agregar(p);
            } else {
                abajo.agregar(p);
            }
        }

        simulador.estructuras.MiListaEnlazada<simulador.modelo.Proceso> listaAUsar;
        if (direccionSubida) {
            if (arriba.getTamano() > 0) listaAUsar = arriba;
            else { direccionSubida = false; listaAUsar = abajo; }
        } else {
            if (abajo.getTamano() > 0) listaAUsar = abajo;
            else { direccionSubida = true; listaAUsar = arriba; }
        }

        if (listaAUsar.getTamano() > 0) {
            int menorDistancia = Integer.MAX_VALUE;
            for (int i = 0; i < listaAUsar.getTamano(); i++) {
                simulador.modelo.Proceso p = listaAUsar.get(i);
                int dist = Math.abs(p.getArchivoQueUsa().getBloqueInicial() - this.posicionCabezal);
                if (dist < menorDistancia) {
                    menorDistancia = dist;
                    elegido = p;
                }
            }
        }
    }
    // --- ALGORITMO C-SCAN ---
    else { 
        simulador.estructuras.MiListaEnlazada<simulador.modelo.Proceso> arribaC = new simulador.estructuras.MiListaEnlazada<>();
        simulador.estructuras.MiListaEnlazada<simulador.modelo.Proceso> abajoC = new simulador.estructuras.MiListaEnlazada<>();

        for (int i = 0; i < lista.getTamano(); i++) {
            simulador.modelo.Proceso p = lista.get(i);
            if (p.getArchivoQueUsa().getBloqueInicial() >= this.posicionCabezal) {
                arribaC.agregar(p);
            } else {
                abajoC.agregar(p);
            }
        }

        simulador.estructuras.MiListaEnlazada<simulador.modelo.Proceso> listaAUsarC;
        int puntoRef;
        if (arribaC.getTamano() > 0) {
            listaAUsarC = arribaC;
            puntoRef = this.posicionCabezal;
        } else {
            listaAUsarC = abajoC;
            puntoRef = 0;
        }

        if (listaAUsarC.getTamano() > 0) {
            int menorDistancia = Integer.MAX_VALUE;
            for (int i = 0; i < listaAUsarC.getTamano(); i++) {
                simulador.modelo.Proceso p = listaAUsarC.get(i);
                int dist = Math.abs(p.getArchivoQueUsa().getBloqueInicial() - puntoRef);
                if (dist < menorDistancia) {
                    menorDistancia = dist;
                    elegido = p;
                }
            }
        }
        if (elegido == null && lista.getTamano() > 0) elegido = lista.get(0);
    }

    // --- RECONSTRUCCIÓN DE LA COLA ---
    for (int i = 0; i < lista.getTamano(); i++) {
        simulador.modelo.Proceso p = lista.get(i);
        if (elegido != null && !p.equals(elegido)) {
            colaDeProcesos.encolar(p);
        }
    }
    
    return elegido;
}
    
    private void actualizarTablaFAT() {
        // 1. Obtenemos el "modelo" de la tabla que diseñamos
        //    (Tu tabla se llama jTable1, lo cual es correcto)
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        
        // 2. Borramos todas las filas viejas para no duplicar datos
        model.setRowCount(0); 
        
        // 3. Recorremos el array de bloques de nuestro disco
        //    (Tu disco se llama miDisco, lo cual es correcto)
        for (Bloque b : miDisco.getBloques()) {
            
            // 4. Añadimos una fila nueva a la tabla por cada bloque
            model.addRow(new Object[]{
                b.getId(),
                b.getPropietario(),
                b.getSiguienteBloque()
            });
        }
    }
    
    private void actualizarVisualizadorGrafico() {
       
        for (int i = 0; i < miDisco.getNumBloques(); i++) {
            
            // Verificamos si el bloque está ocupado
            if (miDisco.getBloque(i).isOcupado()) {
                // Si está ocupado, pintamos el cuadrito de ROJO
                etiquetasBloques[i].setBackground(java.awt.Color.RED);
            } else {
                // Si está libre, lo pintamos de VERDE
                etiquetasBloques[i].setBackground(java.awt.Color.GREEN);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRenombrar;
    private javax.swing.JComboBox<String> cboxModo;
    private javax.swing.JComboBox<String> cboxPolitica;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
